birthday1 = int(input("enteryour own charcater"))
birthday2 =int(input("enteryour own charcater"))
birthday3 = int(input("enteryour own charcater"))
birthday4 = int(input("enteryour own charcater"))
birthday5 = int(input("enteryour own charcater"))
print ("the date the birthday is on birthday 1 is:",birthday1)
print ("the date the birthday is on birthday 2 is:",birthday2)
print ("the date the birthday is on birthday 3 is:",birthday3)
print ("the date the birthday is on birthday 4 is:",birthday4)
print ("the date the birthday is on birthday 5 is:",birthday5)